import { writeFileSync } from 'fs'

const linhas = []
linhas.push("'use client'")
linhas.push("import { useEffect, useState } from 'react'")
linhas.push("import { useRouter } from 'next/navigation'")
linhas.push("import { createClient } from '@supabase/supabase-js'")
linhas.push("import Link from 'next/link'")
linhas.push("import { QrCode, BarChart2, LogOut, Wrench } from 'lucide-react'")
linhas.push("")
linhas.push("const supabase = createClient(")
linhas.push("  process.env.NEXT_PUBLIC_SUPABASE_URL || '',")
linhas.push("  process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || ''")
linhas.push(")")
linhas.push("")
linhas.push("const statusLabel = { enviado: 'Enviado', recebido: 'Recebido', em_analise: 'Em Analise', em_andamento: 'Em Andamento', resolvido: 'Resolvido' }")
linhas.push("const urgenciaCor = { baixa: 'bg-gray-100 text-gray-600', media: 'bg-yellow-100 text-yellow-700', alta: 'bg-orange-100 text-orange-700', muito_alta: 'bg-red-100 text-red-700' }")
linhas.push("const urgenciaLabel = { baixa: 'Baixa', media: 'Media', alta: 'Alta', muito_alta: 'Muito Alta' }")
linhas.push("")
linhas.push("export default function AdminPage() {")
linhas.push("  const router = useRouter()")
linhas.push("  const [chamados, setChamados] = useState([])")
linhas.push("  const [filtroStatus, setFiltroStatus] = useState('')")
linhas.push("  const [filtroUrgencia, setFiltroUrgencia] = useState('')")
linhas.push("  const [carregando, setCarregando] = useState(true)")
linhas.push("")
linhas.push("  useEffect(() => {")
linhas.push("    supabase.auth.getSession().then(({ data }) => {")
linhas.push("      if (!data.session) { router.push('/admin/login'); return }")
linhas.push("      carregarChamados()")
linhas.push("    })")
linhas.push("  }, [])")
linhas.push("")
linhas.push("  async function carregarChamados() {")
linhas.push("    setCarregando(true)")
linhas.push("    const { data } = await supabase.from('chamados').select('*').order('criado_em', { ascending: false })")
linhas.push("    setChamados(data || [])")
linhas.push("    setCarregando(false)")
linhas.push("  }")
linhas.push("")
linhas.push("  async function sair() {")
linhas.push("    await supabase.auth.signOut()")
linhas.push("    router.push('/admin/login')")
linhas.push("  }")
linhas.push("")
linhas.push("  const filtrados = chamados.filter(c => {")
linhas.push("    if (filtroStatus && c.status !== filtroStatus) return false")
linhas.push("    if (filtroUrgencia && c.urgencia !== filtroUrgencia) return false")
linhas.push("    return true")
linhas.push("  })")
linhas.push("")
linhas.push("  const emAberto = chamados.filter(c => c.status !== 'resolvido').length")
linhas.push("  const resolvidos = chamados.filter(c => c.status === 'resolvido').length")
linhas.push("  const muitoAlta = chamados.filter(c => c.urgencia === 'muito_alta' && c.status !== 'resolvido').length")
linhas.push("")
linhas.push("  return (")
linhas.push("    <main className='min-h-screen bg-gray-50 flex'>")
linhas.push("")
linhas.push("      {/* Sidebar */}")
linhas.push("      <aside className='w-20 bg-gray-900 flex flex-col items-center justify-between py-6 flex-shrink-0'>")
linhas.push("        <div className='flex flex-col items-center gap-1'>")
linhas.push("          <div className='bg-yellow-400 rounded-xl w-12 h-12 flex items-center justify-center'>")
linhas.push("            <Wrench size={22} className='text-gray-900' />")
linhas.push("          </div>")
linhas.push("          <span className='text-white text-xs font-bold mt-1'>A.S</span>")
linhas.push("        </div>")
linhas.push("        <div className='flex flex-col items-center gap-6'>")
linhas.push("          <Link href='/admin/qrcodes' className='flex flex-col items-center gap-1 group'>")
linhas.push("            <div className='bg-gray-700 group-hover:bg-yellow-400 rounded-xl w-12 h-12 flex items-center justify-center transition'>")
linhas.push("              <QrCode size={20} className='text-white group-hover:text-gray-900 transition' />")
linhas.push("            </div>")
linhas.push("            <span className='text-gray-400 text-xs group-hover:text-yellow-400 transition text-center leading-tight'>QR Codes</span>")
linhas.push("          </Link>")
linhas.push("          <Link href='/admin/relatorios' className='flex flex-col items-center gap-1 group'>")
linhas.push("            <div className='bg-gray-700 group-hover:bg-yellow-400 rounded-xl w-12 h-12 flex items-center justify-center transition'>")
linhas.push("              <BarChart2 size={20} className='text-white group-hover:text-gray-900 transition' />")
linhas.push("            </div>")
linhas.push("            <span className='text-gray-400 text-xs group-hover:text-yellow-400 transition text-center leading-tight'>Relatorios</span>")
linhas.push("          </Link>")
linhas.push("          <button onClick={sair} className='flex flex-col items-center gap-1 group'>")
linhas.push("            <div className='bg-gray-700 group-hover:bg-red-500 rounded-xl w-12 h-12 flex items-center justify-center transition'>")
linhas.push("              <LogOut size={20} className='text-white transition' />")
linhas.push("            </div>")
linhas.push("            <span className='text-gray-400 text-xs group-hover:text-red-400 transition'>Sair</span>")
linhas.push("          </button>")
linhas.push("        </div>")
linhas.push("      </aside>")
linhas.push("")
linhas.push("      {/* Conteudo principal */}")
linhas.push("      <div className='flex-1 p-6 overflow-auto'>")
linhas.push("")
linhas.push("        {/* Header */}")
linhas.push("        <div className='mb-6'>")
linhas.push("          <h1 className='text-2xl font-bold text-gray-800'>Painel de Chamados</h1>")
linhas.push("          <p className='text-sm text-gray-500'>Manutencao Predial</p>")
linhas.push("        </div>")
linhas.push("")
linhas.push("        {/* Cards de resumo */}")
linhas.push("        <div className='grid grid-cols-3 gap-4 mb-6'>")
linhas.push("          <div className='bg-white rounded-2xl shadow p-5'>")
linhas.push("            <p className='text-xs text-gray-400 mb-1'>Total de Chamados</p>")
linhas.push("            <p className='text-3xl font-black text-gray-800'>{chamados.length}</p>")
linhas.push("          </div>")
linhas.push("          <div className='bg-white rounded-2xl shadow p-5'>")
linhas.push("            <p className='text-xs text-gray-400 mb-1'>Em Aberto</p>")
linhas.push("            <p className='text-3xl font-black text-yellow-400'>{emAberto}</p>")
linhas.push("          </div>")
linhas.push("          <div className='bg-white rounded-2xl shadow p-5'>")
linhas.push("            <p className='text-xs text-gray-400 mb-1'>Urgencia Muito Alta</p>")
linhas.push("            <p className='text-3xl font-black text-red-500'>{muitoAlta}</p>")
linhas.push("          </div>")
linhas.push("        </div>")
linhas.push("")
linhas.push("        {/* Filtros */}")
linhas.push("        <div className='flex gap-2 mb-4'>")
linhas.push("          <select value={filtroStatus} onChange={e => setFiltroStatus(e.target.value)}")
linhas.push("            className='border border-gray-200 rounded-xl px-3 py-2 text-sm focus:outline-none bg-white'>")
linhas.push("            <option value=''>Todos os status</option>")
linhas.push("            {Object.entries(statusLabel).map(([v, l]) => <option key={v} value={v}>{l}</option>)}")
linhas.push("          </select>")
linhas.push("          <select value={filtroUrgencia} onChange={e => setFiltroUrgencia(e.target.value)}")
linhas.push("            className='border border-gray-200 rounded-xl px-3 py-2 text-sm focus:outline-none bg-white'>")
linhas.push("            <option value=''>Todas as urgencias</option>")
linhas.push("            {Object.entries(urgenciaLabel).map(([v, l]) => <option key={v} value={v}>{l}</option>)}")
linhas.push("          </select>")
linhas.push("          <span className='text-sm text-gray-400 self-center ml-2'>{filtrados.length} chamados</span>")
linhas.push("        </div>")
linhas.push("")
linhas.push("        {/* Lista de chamados */}")
linhas.push("        {carregando && <p className='text-gray-400 text-sm'>Carregando...</p>}")
linhas.push("        <div className='flex flex-col gap-3'>")
linhas.push("          {filtrados.map(c => (")
linhas.push("            <Link key={c.id} href={'/admin/chamado/' + c.id}")
linhas.push("              className='bg-white rounded-2xl shadow p-4 hover:shadow-md transition block'>")
linhas.push("              <div className='flex justify-between items-start mb-2'>")
linhas.push("                <span className='font-bold text-gray-800'>{c.codigo_unico}</span>")
linhas.push("                <span className={urgenciaCor[c.urgencia] + ' text-xs px-2 py-1 rounded-full font-medium'}>")
linhas.push("                  {urgenciaLabel[c.urgencia]}")
linhas.push("                </span>")
linhas.push("              </div>")
linhas.push("              <p className='text-sm text-gray-600 mb-1'>{c.tipo_problema}</p>")
linhas.push("              <p className='text-xs text-gray-400 truncate mb-3'>{c.descricao}</p>")
linhas.push("              <div className='flex justify-between items-center'>")
linhas.push("                <span className='text-xs bg-gray-100 text-gray-600 px-2 py-1 rounded-full'>{statusLabel[c.status]}</span>")
linhas.push("                <span className='text-xs text-gray-400'>{new Date(c.criado_em).toLocaleDateString('pt-BR')}</span>")
linhas.push("              </div>")
linhas.push("            </Link>")
linhas.push("          ))}")
linhas.push("        </div>")
linhas.push("      </div>")
linhas.push("    </main>")
linhas.push("  )")
linhas.push("}")

writeFileSync("app/admin/page.tsx", linhas.join("\n"))
console.log("Painel ADM atualizado!")